### ISSUE TITLE
Non-standard SSH Port ?

### ISSUE THREAD

**Issue by cwps** [seanh/snapshotter#23]
Hi,
Is there any command line to add to sync from remote server that using a non-standard ssh port? Or is not possible for this version?

Thanks.

**Comment by seanh** [comment]
Could you try:

    snapshotter -e 'ssh -p 1002' SRC DEST

and let me know if that works?

But the adding the trailing slash sounds like a bug - should be fixed.

**Comment by cwps** [comment]
Still not working.
The output is like this:
```
-e /home/myuser/backup_web ssh -p 1002/
```
 
Here's the full INFO, after I type the command:
```shell
INFO:snapshotter:rsync --archive --partial --partial-dir=partially_transferred_files --one-file-system --delete --delete-excluded --itemize-changes --link-dest=../latest.snapshot --human-readable --quiet --compress --fuzzy -e /home/myuser/backup_web ssh -p 1002/ remoteuser@remotehost:/home/www/myweb.com/incomplete.snapshot
...
```

**Comment by seanh** [comment]
Ok, definitely a bug, it should be pretty simple to fix
